name: 'Egineering-Change'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of the input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time you greeted someone'
runs:
  using: 'node12'
  main: 'dist/index.js'

